
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ANGEL JIMENEZ
 */
public class NewJFrame extends javax.swing.JFrame {

String[] preguntas ={
    
    "Como se llama la capital de mexico?",
    "Nombre del presidente de mexico actual?",
    "En cual continente esta mexico?",
    "En que idioma se habla mexico?"

    };

String[][] opcciones= {
    {"Ciudad de mexico","Estado de mexico","Distrito federal","Dubai"},
    {"Enrique","Andres Mauel","Felipe","Carlos"},   
    {"Africa","Asia","America","Europa"},
    {"Ingles","Frances","Italiano","Castellano"}
  
    
    
    
    
    
    
};

char[] respuestas = {
    'A',
    'B',
    'C',
    'D',


    
};

char adivina;
char respuesta;
int index;
int correctas =0;
int total_preguntas=preguntas.length;
int resultado;
int segundos =10;

    Timer timer= new Timer(1000, new ActionListener(){
    @Override
    public void actionPerformed(ActionEvent e){
        
        segundos--;
        labelSegundos.setText(String.valueOf(segundos));
        if(segundos<=0){
            verRespuesta();
        }
    }
});

   public NewJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        siguientePregunta();
        
     }
   
   private void verRespuesta(){
       
       timer.stop();
        botonA.setEnabled(false);
        botonB.setEnabled(false);
        botonC.setEnabled(false);
        botonD.setEnabled(false);
                            
                            
        if(respuestas[index]!='A'){
           
        }    
                                      
        if(respuestas[index]!='B'){
           
        }   
                                      
        if(respuestas[index]!='C'){
            
        }   
                                      
        if(respuestas[index]!='D'){
           
                     
        Timer pause = new Timer(2000, new ActionListener(){
         @Override
        public void actionPerformed(ActionEvent e){   
            
            
         respuestaA.setForeground(Color.black);
         respuestaB.setForeground(Color.black);
         respuestaC.setForeground(Color.black);
         respuestaD.setForeground(Color.black);
         
        respuesta =' ';
        segundos=10;
        labelSegundos.setText(String.valueOf(segundos));
        botonA.setEnabled(true);
        botonB.setEnabled(true);
        botonC.setEnabled(true);
        botonD.setEnabled(true);
         index++;
         siguientePregunta();
         
      }
      
      });
        
        pause.setRepeats(false);
        pause.start();
        
        }
        
   
  
           
        botonA.setEnabled(false);
        botonB.setEnabled(false);
        botonC.setEnabled(false);
        botonD.setEnabled(false);
        
        resultado = (int)((correctas/(double)total_preguntas)*100);
        field.setText("Resultado");
        area.setText("");
        respuestaA.setText("");
         respuestaB.setText("");
          respuestaC.setText("");
           respuestaD.setText("");
  
           
         buenas.setText("correctas\n"+"("+ correctas+ "/" + total_preguntas+ ")");
         porcentage.setText("Porcentage\n"+resultado+"%");
         labelSegundos.setVisible(false);
            
        }
        private void siguientePregunta(){
            
        if(index>=total_preguntas){
      
            
        }else{
         field.setText("Pregunta:"+ (index+1));
         area.setText(preguntas[index]);
           respuestaA.setText(opcciones[index][0]);
           respuestaB.setText(opcciones[index][1]);
           respuestaC.setText(opcciones[index][2]);
           respuestaD.setText(opcciones[index][3]);

                   
        timer.start();
        
        }        
        }
        
        
        
        
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        field = new javax.swing.JTextField();
        area = new javax.swing.JTextField();
        botonA = new javax.swing.JButton();
        botonB = new javax.swing.JButton();
        botonC = new javax.swing.JButton();
        botonD = new javax.swing.JButton();
        respuestaA = new javax.swing.JLabel();
        respuestaB = new javax.swing.JLabel();
        respuestaC = new javax.swing.JLabel();
        respuestaD = new javax.swing.JLabel();
        buenas = new javax.swing.JLabel();
        porcentage = new javax.swing.JLabel();
        labelSegundos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        field.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        field.setText("Pregunta: 1 ");
        field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldActionPerformed(evt);
            }
        });

        area.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        area.setText("¿como se llama la capital de Mexico?");
        area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaActionPerformed(evt);
            }
        });

        botonA.setText("A");
        botonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAActionPerformed(evt);
            }
        });

        botonB.setText("B");
        botonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBActionPerformed(evt);
            }
        });

        botonC.setText("C");
        botonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCActionPerformed(evt);
            }
        });

        botonD.setText("D");
        botonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDActionPerformed(evt);
            }
        });

        respuestaA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        respuestaA.setText("Ciudad de mexico");

        respuestaB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        respuestaB.setText("Estado de Mexico");

        respuestaC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        respuestaC.setText("Distrito Federal");

        respuestaD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        respuestaD.setText("Dubai");

        buenas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buenas.setText("BUENAS");

        porcentage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        porcentage.setText("PORCENTAGE");

        labelSegundos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelSegundos.setText("10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(field)
                            .addComponent(area, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE))
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonA, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(botonB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(260, 260, 260)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(respuestaA)
                            .addComponent(respuestaB)
                            .addComponent(respuestaC)
                            .addComponent(respuestaD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(porcentage)
                            .addComponent(buenas)
                            .addComponent(labelSegundos))))
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonD, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(respuestaD))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonA, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(respuestaA)
                            .addComponent(buenas))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonB, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(respuestaB)
                            .addComponent(porcentage))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonC, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(respuestaC))
                        .addGap(1, 1, 1)
                        .addComponent(labelSegundos)
                        .addGap(138, 138, 138)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaActionPerformed

    private void botonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAActionPerformed
        // TODO add your handling code here:
        botonA.setEnabled(false);
            botonB.setEnabled(false);
                botonC.setEnabled(false);
                    botonD.setEnabled(false);
      if (evt.getSource()==botonA){
          respuesta ='A';
          if(respuesta==respuestas[index]){
              correctas++;
              
          }
      }  
              verRespuesta();      
    }//GEN-LAST:event_botonAActionPerformed

    private void botonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBActionPerformed
        // TODO add your handling code here:
          botonA.setEnabled(false);
            botonB.setEnabled(false);
                botonC.setEnabled(false);
                    botonD.setEnabled(false);
      if (evt.getSource()==botonB){
          respuesta ='B';
          if(respuesta==respuestas[index]){
              correctas++;
              
          }
      }  
              verRespuesta();  
    }//GEN-LAST:event_botonBActionPerformed

    private void botonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCActionPerformed
        // TODO add your handling code here:
         botonA.setEnabled(false);
            botonB.setEnabled(false);
                botonC.setEnabled(false);
                    botonD.setEnabled(false);
      if (evt.getSource()==botonC){
          respuesta ='C';
          if(respuesta==respuestas[index]){
              correctas++;
              
          }
      }  
              verRespuesta();  
    }//GEN-LAST:event_botonCActionPerformed

    private void botonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDActionPerformed
        // TODO add your handling code here:
         botonA.setEnabled(false);
            botonB.setEnabled(false);
                botonC.setEnabled(false);
                    botonD.setEnabled(false);
      if (evt.getSource()==botonD){
          respuesta ='D';
          if(respuesta==respuestas[index]){
              correctas++;
              
          }
      }  
              verRespuesta();  
    }//GEN-LAST:event_botonDActionPerformed

    private void fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField area;
    private javax.swing.JButton botonA;
    private javax.swing.JButton botonB;
    private javax.swing.JButton botonC;
    private javax.swing.JButton botonD;
    private javax.swing.JLabel buenas;
    private javax.swing.JTextField field;
    private javax.swing.JLabel labelSegundos;
    private javax.swing.JLabel porcentage;
    private javax.swing.JLabel respuestaA;
    private javax.swing.JLabel respuestaB;
    private javax.swing.JLabel respuestaC;
    private javax.swing.JLabel respuestaD;
    // End of variables declaration//GEN-END:variables
}


